import type { AdminMetric, Product, StorySeries } from "@/lib/types";

export const brand = {
  name: "NOIRVEN",
  cnName: "诺梵",
  proposition: "每一次归属，都是一次拯救。",
  secondary: "不由多数定义，只由唯一确认。",
  story:
    "Noirven 诺梵相信，真正独一无二的作品，不该被流行审判。每一件作品都有自己的编号，进入七日拍卖。一旦被确认，它从此只归一人；若尚未归属，它不会被放弃，而是继续等待下一次被看见。",
  cta: "进入七日拍卖",
  storyCta: "品牌故事",
};

export const materialLibrary = {
  metals: ["玫瑰金", "雕金", "黄金", "铂金", "钯金", "钛金属", "黑铑铂金", "陨铁", "黑陶瓷", "锆陶瓷"],
  stones: [
    "天然白钻",
    "彩色宝石",
    "青金石",
    "贝母",
    "孔雀石",
    "蓝宝石",
    "祖母绿",
    "红宝石",
    "帕拉伊巴碧玺",
    "沙弗莱石",
    "尖晶石",
    "坦桑石",
    "欧泊",
    "月光石",
    "黑贝母",
    "海蓝宝",
    "烟晶",
    "白水晶",
    "玉髓",
    "珍珠母贝",
  ],
  craft: [
    "珐琅彩",
    "钢琴烤漆",
    "鎏金",
    "鎏彩",
    "景泰蓝",
    "玑镂雕纹",
    "微密镶",
    "隐秘式镶嵌",
    "雪花镶",
    "手工錾刻",
    "错金银",
    "冷珐琅",
    "半透明珐琅",
    "贝母薄片镶嵌",
    "钛金属阳极氧化",
    "陶瓷烧结",
    "镜面抛光",
    "拉丝雾面",
  ],
};

export const materialNarratives = [
  {
    title: "Night Metal",
    zhTitle: "夜色金属",
    story: "黑铑铂金、钛金属与陨铁承载低声、克制和反转，不负责闪耀，只负责留下无法复制的轮廓。",
    materials: ["黑铑铂金", "钛金属", "陨铁"],
    craft: ["拉丝雾面", "镜面抛光", "钛金属阳极氧化"],
  },
  {
    title: "Living Blue",
    zhTitle: "会呼吸的蓝",
    story: "青金石、海蓝宝与帕拉伊巴碧玺用于等待、归潮和远行，让蓝色不只是颜色，而是一种被重新认出的方向。",
    materials: ["青金石", "海蓝宝", "帕拉伊巴碧玺"],
    craft: ["隐秘式镶嵌", "半透明珐琅", "水纹雕刻"],
  },
  {
    title: "Archive Light",
    zhTitle: "档案之光",
    story: "贝母、黑贝母、月光石和欧泊像被保存的记忆，适合月相、告别、秘密与迟来的理解。",
    materials: ["贝母", "黑贝母", "月光石", "欧泊"],
    craft: ["贝母薄片镶嵌", "玑镂雕纹", "微刻封存线"],
  },
  {
    title: "Verdict Green",
    zhTitle: "裁决之绿",
    story: "孔雀石、沙弗莱石与祖母绿为 Justice of One 建立证据感，像一道安静但不可反驳的判定。",
    materials: ["孔雀石", "沙弗莱石", "祖母绿"],
    craft: ["景泰蓝", "手工錾刻", "错金银"],
  },
  {
    title: "Burned Bloom",
    zhTitle: "灰烬盛开",
    story: "黑陶瓷、烟晶、暗红珐琅和红宝石表达重建之后的生命感，让花不是柔弱符号，而是废墟里的证词。",
    materials: ["黑陶瓷", "烟晶", "红宝石"],
    craft: ["陶瓷烧结", "冷珐琅", "局部鎏彩"],
  },
  {
    title: "Soft Armor",
    zhTitle: "柔性盔甲",
    story: "钯金、碳纤维、粉玉髓和白玛瑙服务于温柔盔甲：柔软不是退让，而是带边界的保护。",
    materials: ["钯金", "碳纤维", "粉玉髓", "白玛瑙"],
    craft: ["碳纤维层压", "微密镶", "钢琴烤漆"],
  },
];

export const storySeries: StorySeries[] = [
  {
    id: "still-here",
    name: "Still Here",
    zhName: "仍在这里",
    theme: "低谷之后仍然站在这里。",
    emotionalLine: "我还在，所以光也还在。",
    description:
      "为从低谷中重新认领自己的人而生。作品常带有不完全闭合的曲线、克制的裂隙和一个微小光点，像证明：伤口之后，仍有形态。",
    categories: ["ring", "bracelet", "brooch"],
    materials: ["铂金", "玫瑰金", "黑铑铂金", "天然白钻", "烟晶"],
    craft: ["珐琅彩", "钢琴烤漆", "半透明珐琅", "微密镶"],
    visualMemory: ["不完全闭合曲线", "小面积光点", "隐藏编号", "克制裂隙"],
    ipHook: "一位匿名买家 Still Here 拍下 N-0007 后，Noirven 确定了尚未归属的作品继续等待的规则。",
  },
  {
    id: "unclaimed-star",
    name: "Awaiting Star",
    zhName: "待归之星",
    theme: "有些光不属于人群，只等待唯一能读懂它的人。",
    emotionalLine: "不是无人喜欢，只是尚未遇见唯一的主人。",
    description:
      "为长期等待、最终与唯一主人互相确认的存在而生。作品避免直接星形，而用单颗宝石、悬浮细线和大面积留白表达命定归属之前的安静光芒。",
    categories: ["necklace", "stud", "earring"],
    materials: ["铂金", "青金石", "珍珠母贝", "帕拉伊巴碧玺", "天然白钻"],
    craft: ["珐琅彩", "鎏彩", "隐秘式镶嵌", "贝母薄片镶嵌"],
    visualMemory: ["单颗宝石", "悬浮细线", "大面积留白", "非具象星点"],
    ipHook: "每一轮尚未归属都会成为作品档案的一部分：它不是被遗忘，而是在等一个能与它互相确认的人。",
  },
  {
    id: "seventh-light",
    name: "Seventh Light",
    zhName: "第七日的光",
    theme: "七日之后，光没有消失，而是归于某个人。",
    emotionalLine: "第七日，光有了归属。",
    description:
      "为七日拍卖机制而生的核心系列。七段细线、偏移亮点和倒计时刻度构成隐性记忆，表达归属发生在最后一刻。",
    categories: ["ring", "earring", "watch"],
    materials: ["黄金", "玫瑰金", "彩色宝石", "尖晶石", "天然白钻"],
    craft: ["鎏金", "鎏彩", "景泰蓝", "雪花镶"],
    visualMemory: ["七段细线", "倒计时刻度", "偏移亮点", "不对称结构"],
    ipHook: "每一件 Seventh Light 都有一段最后一小时的命运反转。",
  },
  {
    id: "justice-of-one",
    name: "Justice of One",
    zhName: "唯一的证明",
    theme: "让被低估的独特，获得一次公平展示。",
    emotionalLine: "不由多数定义，只由唯一确认。",
    description:
      "为被低估、被误读、但仍然锋利完整的存在而生。作品强调平衡线、偏心宝石和一处像证据一样的光。",
    categories: ["brooch", "bracelet", "ring"],
    materials: ["雕金", "孔雀石", "沙弗莱石", "祖母绿", "天然白钻"],
    craft: ["景泰蓝", "鎏金", "手工錾刻", "错金银"],
    visualMemory: ["平衡线", "偏心结构", "锋利转折", "单颗宝石证据"],
    ipHook: "作品像一份无声证词，不需要多数投票来证明自己的价值。",
  },
  {
    id: "ash-garden",
    name: "Ash Garden",
    zhName: "灰烬花园",
    theme: "从被烧毁的地方，重新长出不需要许可的花。",
    emotionalLine: "灰烬不是结束，是另一种盛开。",
    description:
      "为经历过崩塌、失去、沉默重建的人而生。作品不以明亮金属为主，而用黑陶瓷、烟晶、黑曜石、暗红珐琅和钛金属形成冷静的生命感；花不是柔弱符号，而是从裂面里长出的证据。",
    categories: ["ring", "brooch", "earring"],
    materials: ["黑陶瓷", "钛金属", "烟晶", "黑曜石", "暗红珐琅", "陨铁"],
    craft: ["微雕", "冷珐琅", "陶瓷烧结", "局部鎏彩", "黑铑封层"],
    visualMemory: ["焦黑裂面", "细小花芽", "暗红光点", "非对称重生线"],
    ipHook: "Ash Garden 可以延展成废墟、幸存者、秘密花园与重建城市的长线叙事，每一件作品都是灾后第一朵花。",
  },
  {
    id: "tide-return",
    name: "Tide Return",
    zhName: "归潮",
    theme: "被海带走的东西，会以另一种光回来。",
    emotionalLine: "失去不是沉没，是等待下一次涨潮。",
    description:
      "为离开、迁徙、远行后重新回到自我的人而生。作品以贝母、海蓝宝、青金石、珍珠母贝与透明树脂水纹为记忆，弱化金属存在，让材质像潮汐一样包裹身体。",
    categories: ["necklace", "bracelet", "stud"],
    materials: ["贝母", "海蓝宝", "青金石", "欧泊", "珍珠母贝", "雾面钛"],
    craft: ["贝母薄片镶嵌", "透明珐琅", "水纹雕刻", "冷色鎏彩", "隐秘式镶嵌"],
    visualMemory: ["潮汐弧线", "半透明水纹", "漂流编号", "内侧回声线"],
    ipHook: "Tide Return 可以延展为漂流瓶、失物招领、海边旧信和归来的旅人，适合后续小说与短剧支线。",
  },
  {
    id: "tender-armor",
    name: "Tender Armor",
    zhName: "温柔盔甲",
    theme: "温柔不是退让，是选择不被击碎。",
    emotionalLine: "我柔软，但不会再被轻易打碎。",
    description:
      "为外表温和、内里坚定的人而生。作品使用碳纤维、雾面钛、粉玉髓、白玛瑙与钢琴烤漆，形成轻而坚固的护甲语言；结构可贴合身体，却保留清晰边界。",
    categories: ["bracelet", "ring", "watch"],
    materials: ["碳纤维", "雾面钛", "钯金", "粉玉髓", "白玛瑙", "钢琴烤漆"],
    craft: ["碳纤维层压", "钛金属拉丝", "钢琴烤漆", "玉髓包镶", "微密镶"],
    visualMemory: ["柔弧护甲", "隐藏铰链", "粉白内光", "边界切线"],
    ipHook: "Tender Armor 可以发展为女性守护、边界感、自我修复与城市战衣的 IP 线，适合未来游戏装备系统。",
  },
  {
    id: "moon-archive",
    name: "Moon Archive",
    zhName: "月相档案",
    theme: "月亮记得你没有说出口的每一次告别。",
    emotionalLine: "不是忘记了，只是被月光保存。",
    description:
      "为不愿公开伤口、却仍然保存记忆的人而生。作品以月光石、黑贝母、青金石、白水晶和浅色珐琅构成档案页般的层次，强调半透明、留白与编号封存。",
    categories: ["necklace", "stud", "brooch"],
    materials: ["月光石", "黑贝母", "青金石", "白水晶", "坦桑石", "浅色珐琅"],
    craft: ["半透明珐琅", "贝母薄片镶嵌", "玑镂雕纹", "水晶切面", "微刻封存线"],
    visualMemory: ["月相切片", "档案封条", "半透明留白", "低声编号"],
    ipHook: "Moon Archive 可以沉淀为秘密档案馆、月相日记、失物记忆和角色过往支线，为后续小说和短剧提供情感线索。",
  },
];

export const storyChapters = [
  {
    code: "CH-01",
    seriesId: "ash-garden",
    title: "灰烬花园的第一封信",
    summary:
      "一位买家没有留下真名，只写下：我不是想回到从前，我只是想证明废墟也能开花。于是 Ash Garden 成为 Noirven 第一条非明亮金属主导的故事线。",
    emotion: "重建、幸存、反转",
  },
  {
    code: "CH-02",
    seriesId: "tide-return",
    title: "归潮的蓝色收据",
    summary:
      "N-0520 曾经连续等待数轮，直到一位远行多年的人在涨潮日拍下它。她说：我不是回来找谁，我是回来确认自己。",
    emotion: "离开、回归、救赎",
  },
  {
    code: "CH-03",
    seriesId: "tender-armor",
    title: "温柔盔甲的边界",
    summary:
      "它看起来轻，实际很难被折断。买家把它戴在手腕内侧，像把一句没有说出口的“不”刻进身体。",
    emotion: "边界、保护、清醒",
  },
  {
    code: "CH-04",
    seriesId: "moon-archive",
    title: "月相档案馆",
    summary:
      "每一件 Moon Archive 都像一页被月光封存的档案。它不替人遗忘，只负责把无法说出口的部分保存到被理解那天。",
    emotion: "记忆、告别、保存",
  },
  {
    code: "CH-05",
    seriesId: "unclaimed-star",
    title: "待归之星的静默轨道",
    summary:
      "它没有寻找所有人的目光，只在自己的轨道上发亮。直到某个夜晚，一个人停下来，说：这不是等待我购买，它像是在等待我承认自己。",
    emotion: "等待、命定、唯一确认",
  },
  {
    code: "CH-06",
    seriesId: "justice-of-one",
    title: "裁决之绿的证词",
    summary:
      "孔雀石的纹路像一份没有签名的证词，沙弗莱石在偏心处发光。它提醒佩戴者：真正的价值不需要多数人举手。",
    emotion: "正义、证明、反转",
  },
  {
    code: "CH-07",
    seriesId: "still-here",
    title: "黑铑裂隙里的白钻",
    summary:
      "一枚白钻被放在最克制的裂隙旁，不像装饰，更像一句仍然活着的回答。Still Here 从不掩饰裂痕，它把裂痕变成光经过的地方。",
    emotion: "存活、修复、微光",
  },
  {
    code: "CH-08",
    seriesId: "seventh-light",
    title: "最后一小时的红色指针",
    summary:
      "第七日最后一小时，红宝石像被推迟的心跳。它不催促任何人，只把归属发生前的紧张与温柔固定在金线之间。",
    emotion: "倒计时、归属、命运",
  },
];

export const dailyProductSeeds = [
  {
    serial: "N-0501",
    seriesId: "ash-garden",
    category: "ring",
    zhTitle: "灰烬花园烬花戒",
    materialLine: "黑陶瓷 / 烟晶 / 暗红珐琅 / 雾面钛",
    craftLine: "哑光陶瓷烧结 / 冷珐琅 / 微雕花芽",
    storyLine: "从裂面里长出的花，不需要春天批准。",
    imagePrompt:
      "Noirven one-of-one luxury open ring, black ceramic and smoky quartz, dark red enamel flower bud growing from a cracked matte titanium surface, minimal high jewelry render, porcelain background, no logo, museum lighting",
  },
  {
    serial: "N-0502",
    seriesId: "tide-return",
    category: "necklace",
    zhTitle: "归潮贝母水纹项链",
    materialLine: "贝母 / 海蓝宝 / 透明水晶 / 青金石",
    craftLine: "贝母薄片镶嵌 / 透明珐琅 / 水纹雕刻",
    storyLine: "失去不是沉没，是等待下一次涨潮。",
    imagePrompt:
      "Noirven one-of-one luxury necklace, mother of pearl and aquamarine waterline pendant with lapis lazuli inlay, translucent enamel tide pattern, asymmetric poetic high jewelry, porcelain background, no logo",
  },
  {
    serial: "N-0503",
    seriesId: "tender-armor",
    category: "bracelet",
    zhTitle: "温柔盔甲柔锋手环",
    materialLine: "碳纤维 / 雾面钛 / 粉玉髓 / 钢琴烤漆",
    craftLine: "碳纤维层压 / 钛金属拉丝 / 玉髓包镶",
    storyLine: "我柔软，但不会再被轻易打碎。",
    imagePrompt:
      "Noirven one-of-one luxury bracelet, soft armor language, carbon fiber layered cuff with matte titanium, pale pink chalcedony and piano lacquer, protective but elegant silhouette, porcelain background, no logo",
  },
  {
    serial: "N-0504",
    seriesId: "moon-archive",
    category: "brooch",
    zhTitle: "月相档案藏月胸针",
    materialLine: "黑贝母 / 月光石 / 白水晶 / 浅色珐琅",
    craftLine: "半透明珐琅 / 水晶切面 / 微刻封存线",
    storyLine: "不是忘记了，只是被月光保存。",
    imagePrompt:
      "Noirven one-of-one luxury brooch, moon archive concept, black mother of pearl, moonstone and white crystal, translucent enamel archive seals, quiet poetic high jewelry, porcelain background, no logo",
  },
  {
    serial: "N-0505",
    seriesId: "unclaimed-star",
    category: "necklace",
    zhTitle: "待归之星帕拉伊巴项链",
    materialLine: "铂金 / 帕拉伊巴碧玺 / 珍珠母贝 / 天然白钻",
    craftLine: "隐秘式镶嵌 / 贝母薄片镶嵌 / 半透明珐琅",
    storyLine: "有些光不属于人群，只等待唯一能读懂它的人。",
    imagePrompt:
      "Noirven one-of-one luxury necklace, awaiting star concept, platinum, paraiba tourmaline, pearl mother-of-pearl and white diamond, floating single-gem composition, vast negative space, porcelain background, no logo",
  },
  {
    serial: "N-0506",
    seriesId: "justice-of-one",
    category: "brooch",
    zhTitle: "唯一的证明裁决绿胸针",
    materialLine: "雕金 / 孔雀石 / 沙弗莱石 / 天然白钻",
    craftLine: "手工錾刻 / 景泰蓝 / 错金银 / 微密镶",
    storyLine: "真正的价值，不需要多数人举手。",
    imagePrompt:
      "Noirven one-of-one luxury brooch, justice of one concept, carved gold, malachite and tsavorite, cloisonne-inspired blue line, evidence-like green gem offset, high jewelry render, porcelain background, no logo",
  },
  {
    serial: "N-0507",
    seriesId: "still-here",
    category: "ring",
    zhTitle: "仍在这里黑铑裂光戒",
    materialLine: "黑铑铂金 / 玫瑰金 / 烟晶 / 天然白钻",
    craftLine: "钢琴烤漆 / 半透明珐琅 / 微密镶",
    storyLine: "裂痕不是终点，是光经过的地方。",
    imagePrompt:
      "Noirven one-of-one luxury open ring, still here concept, black rhodium platinum and rose gold, smoky quartz, tiny white diamond beside a lacquer rift, restrained emotional high jewelry, porcelain background, no logo",
  },
  {
    serial: "N-0508",
    seriesId: "seventh-light",
    category: "watch",
    zhTitle: "第七日红曜腕表",
    materialLine: "黄金 / 玫瑰金 / 红宝石 / 贝母盘面",
    craftLine: "玑镂雕纹 / 鎏彩 / 雪花镶 / 微刻时标",
    storyLine: "最后一小时，光有了心跳。",
    imagePrompt:
      "Noirven one-of-one luxury jewelry watch, seventh light concept, gold and rose gold, ruby crown, mother of pearl dial, seven fine markers, guilloche texture, poetic countdown feeling, porcelain background, no logo",
  },
  {
    serial: "N-0509",
    seriesId: "tide-return",
    category: "bracelet",
    zhTitle: "归潮欧泊回声手环",
    materialLine: "欧泊 / 海蓝宝 / 雾面钛 / 青金石",
    craftLine: "水纹雕刻 / 冷色鎏彩 / 隐秘式镶嵌",
    storyLine: "回来不是重复旧路，是以另一种光抵达。",
    imagePrompt:
      "Noirven one-of-one luxury bracelet, tide return concept, opal, aquamarine, matte titanium and lapis lazuli, wave echo shape, translucent enamel water texture, high jewelry render, porcelain background, no logo",
  },
  {
    serial: "N-0510",
    seriesId: "tender-armor",
    category: "ring",
    zhTitle: "温柔盔甲钯金守戒",
    materialLine: "钯金 / 白玛瑙 / 粉玉髓 / 天然白钻",
    craftLine: "拉丝雾面 / 玉髓包镶 / 微密镶 / 钢琴烤漆",
    storyLine: "温柔不是退让，是选择不再被击碎。",
    imagePrompt:
      "Noirven one-of-one luxury ring, tender armor concept, palladium, white agate, pink chalcedony and tiny white diamonds, soft protective silhouette with clear boundary lines, porcelain background, no logo",
  },
  {
    serial: "N-0511",
    seriesId: "moon-archive",
    category: "stud",
    zhTitle: "月相档案坦桑耳钉",
    materialLine: "坦桑石 / 黑贝母 / 月光石 / 白水晶",
    craftLine: "玑镂雕纹 / 半透明珐琅 / 微刻封存线",
    storyLine: "月光不替你遗忘，只替你保存。",
    imagePrompt:
      "Noirven one-of-one luxury stud earrings, moon archive concept, tanzanite, black mother of pearl, moonstone and white crystal, archive seal geometry, translucent enamel, porcelain background, no logo",
  },
  {
    serial: "N-0512",
    seriesId: "ash-garden",
    category: "earring",
    zhTitle: "灰烬花园陨铁耳环",
    materialLine: "陨铁 / 黑陶瓷 / 红宝石 / 暗红珐琅",
    craftLine: "陶瓷烧结 / 手工錾刻 / 局部鎏彩 / 冷珐琅",
    storyLine: "废墟里的第一朵花，不需要被允许。",
    imagePrompt:
      "Noirven one-of-one luxury earring, ash garden concept, meteorite, black ceramic, ruby and dark red enamel, burned flower emerging from fractured surface, asymmetrical high jewelry render, porcelain background, no logo",
  },
];

export const products: Product[] = [
  {
    id: "n-0101",
    slug: "still-here-ring-n-0101",
    serial: "N-0101",
    title: "Still Here Riftlight Ring",
    zhTitle: "仍在这里裂光戒",
    seriesId: "still-here",
    category: "ring",
    inspiration: "我还在，所以光也还在。",
    concept:
      "铂金与玫瑰金形成不完全闭合的活口戒臂，黑色钢琴烤漆裂隙旁嵌入一颗天然白钻。它把裂缝变成结构，把低谷之后仍然站立的姿态固定下来。",
    materials: ["铂金", "玫瑰金", "天然白钻"],
    craft: ["钢琴烤漆", "珐琅彩"],
    startPrice: 3888,
    currentPrice: 4728,
    depositAmount: 320,
    bidIncrement: 120,
    bids: 16,
    endsAt: "2026-05-26T21:00:00+08:00",
    status: "live",
    image: "/assets/products/n-0101-still-here-ring.png",
    sizing: "活口戒臂，可按佩戴者手寸微调；内侧保留舒适弧面。",
    engraving: "戒臂内侧刻印 N-0101。",
    pricingBasis: "戒指体量中等，铂金与玫瑰金双金属结构，天然白钻与钢琴烤漆裂隙工艺。",
  },
  {
    id: "n-0102",
    slug: "still-here-bracelet-n-0102",
    serial: "N-0102",
    title: "Still Here Quiet Rift Bracelet",
    zhTitle: "仍在这里静裂手环",
    seriesId: "still-here",
    category: "bracelet",
    inspiration: "不是修补伤口，而是承认伤口之后仍然完整。",
    concept:
      "开放式手环用玫瑰金与铂金保留一处清晰负空间，珐琅裂隙与微钻光点形成 Still Here 系列的识别。",
    materials: ["玫瑰金", "铂金", "天然白钻"],
    craft: ["珐琅彩", "钢琴烤漆"],
    startPrice: 4688,
    currentPrice: 4688,
    depositAmount: 360,
    bidIncrement: 140,
    bids: 0,
    endsAt: "2026-05-27T19:30:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0102-still-here-bracelet.png",
    sizing: "开放式活口手环，适配多数腕围，可由交付前微调弧度。",
    engraving: "手环内侧刻印 N-0102。",
    pricingBasis: "手环体量较大，双金属结构与珐琅/烤漆复合工艺提升起拍价。",
  },
  {
    id: "n-0103",
    slug: "still-here-brooch-n-0103",
    serial: "N-0103",
    title: "Still Here Witness Brooch",
    zhTitle: "仍在这里证光胸针",
    seriesId: "still-here",
    category: "brooch",
    inspiration: "伤口之后，仍有形态。",
    concept:
      "铂金线条被一处黑色烤漆裂隙打断，玫瑰金底面托住微小白钻，像一份安静但不可撤销的证明。",
    materials: ["铂金", "玫瑰金", "天然白钻"],
    craft: ["钢琴烤漆", "雕金"],
    startPrice: 4388,
    currentPrice: 5128,
    depositAmount: 360,
    bidIncrement: 140,
    bids: 11,
    endsAt: "2026-05-25T22:20:00+08:00",
    status: "sold",
    ownerNickname: "Still Here",
    soldAt: "2026-05-18T22:20:00+08:00",
    image: "/assets/products/n-0103-still-here-brooch.png",
    sizing: "胸针背扣为安全锁结构，不涉及尺码；可佩戴于西装、丝巾或礼服。",
    engraving: "胸针背面刻印 N-0103。",
    pricingBasis: "胸针结构复杂，铂金线条、雕金背面与白钻光点共同定价。",
  },
  {
    id: "n-0201",
    slug: "unclaimed-star-pendant-n-0201",
    serial: "N-0201",
    title: "Awaiting Star Lapis Necklace",
    zhTitle: "待归之星星芒项链",
    seriesId: "unclaimed-star",
    category: "necklace",
    inspiration: "不是无人喜欢，只是尚未遇见唯一的主人。",
    concept:
      "青金石与贝母组成非具象悬浮切面，一颗天然白钻被极细铂金线托住。它不画星星，却让等待唯一归属的时刻自己发光。",
    materials: ["铂金", "青金石", "贝母", "天然白钻"],
    craft: ["珐琅彩", "鎏彩"],
    startPrice: 3288,
    currentPrice: 3288,
    depositAmount: 280,
    bidIncrement: 100,
    bids: 0,
    endsAt: "2026-05-28T20:00:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0201-unclaimed-star-pendant.png",
    sizing: "链长可调节，支持锁骨链与常规项链两档佩戴。",
    engraving: "吊坠背面刻印 N-0201。",
    pricingBasis: "吊坠体量克制，青金石、贝母与白钻组合，工艺复杂度中等。",
  },
  {
    id: "n-0202",
    slug: "unclaimed-star-studs-n-0202",
    serial: "N-0202",
    title: "Awaiting Star Whisper Studs",
    zhTitle: "待归之星星语耳钉",
    seriesId: "unclaimed-star",
    category: "stud",
    inspiration: "等待不是空白，是归属发生之前的序章。",
    concept:
      "一对不完全对称耳钉以青金石、贝母和白钻形成悬浮星点，但避开直白星形，让识别来自留白和比例。",
    materials: ["铂金", "青金石", "贝母", "天然白钻"],
    craft: ["珐琅彩"],
    startPrice: 2688,
    currentPrice: 3168,
    depositAmount: 220,
    bidIncrement: 80,
    bids: 7,
    endsAt: "2026-05-24T18:10:00+08:00",
    status: "sold",
    ownerNickname: "Starless",
    soldAt: "2026-05-17T18:10:00+08:00",
    image: "/assets/products/n-0202-unclaimed-star-studs.png",
    sizing: "耳钉为标准针式结构，不涉及尺码。",
    engraving: "耳钉背托刻印 N-0202。",
    pricingBasis: "耳钉体量小，但双材质切面与白钻镶嵌提升起拍价。",
  },
  {
    id: "n-0203",
    slug: "unclaimed-star-earring-n-0203",
    serial: "N-0203",
    title: "Awaiting Star Drift Earring",
    zhTitle: "待归之星星渡耳环",
    seriesId: "unclaimed-star",
    category: "earring",
    inspiration: "被看见之前，它已经独一无二。",
    concept:
      "细长铂金结构悬挂青金石与贝母切面，一颗白钻像被延迟认出的光，整体保持轻盈而不对称。",
    materials: ["铂金", "青金石", "贝母", "天然白钻"],
    craft: ["珐琅彩", "鎏彩"],
    startPrice: 3488,
    currentPrice: 3928,
    depositAmount: 280,
    bidIncrement: 100,
    bids: 8,
    endsAt: "2026-05-26T17:45:00+08:00",
    status: "live",
    image: "/assets/products/n-0203-unclaimed-star-earring.png",
    sizing: "耳环为标准耳针结构，可提供耳夹改造咨询。",
    engraving: "耳环背部微刻 N-0203。",
    pricingBasis: "长耳环结构、青金石/贝母组合和鎏彩细节带来中高起拍价。",
  },
  {
    id: "n-0301",
    slug: "seventh-light-ring-n-0301",
    serial: "N-0301",
    title: "Seventh Light Last Hour Ring",
    zhTitle: "第七日归光戒",
    seriesId: "seventh-light",
    category: "ring",
    inspiration: "第七日，光有了归属。",
    concept:
      "黄金与玫瑰金在活口戒臂上形成七段细线，一颗偏移彩宝打破完美对称，像最后一小时出现的答案。",
    materials: ["黄金", "玫瑰金", "彩色宝石", "天然白钻"],
    craft: ["鎏金", "鎏彩"],
    startPrice: 4188,
    currentPrice: 5368,
    depositAmount: 380,
    bidIncrement: 160,
    bids: 19,
    endsAt: "2026-05-23T21:00:00+08:00",
    status: "live",
    image: "/assets/products/n-0301-seventh-light-ring.png",
    sizing: "活口戒臂，可覆盖常见手寸区间并支持交付前微调。",
    engraving: "戒臂内侧刻印 N-0301。",
    pricingBasis: "Seventh Light 核心系列，彩宝、白钻、双金属和七段线结构共同定价。",
  },
  {
    id: "n-0302",
    slug: "seventh-light-earrings-n-0302",
    serial: "N-0302",
    title: "Seventh Light Turning Earrings",
    zhTitle: "第七日回时耳环",
    seriesId: "seventh-light",
    category: "earring",
    inspiration: "最后一小时的归属反转。",
    concept:
      "一对耳环以七段金线和偏移彩色宝石组成倒计时韵律，左右轻微不对称，仍然保持同一秩序。",
    materials: ["玫瑰金", "黄金", "彩色宝石", "天然白钻"],
    craft: ["鎏金", "鎏彩"],
    startPrice: 3988,
    currentPrice: 3988,
    depositAmount: 320,
    bidIncrement: 140,
    bids: 0,
    endsAt: "2026-05-29T19:20:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0302-seventh-light-earrings.png",
    sizing: "标准耳针结构，可提供耳夹改造咨询。",
    engraving: "耳环背面刻印 N-0302。",
    pricingBasis: "耳环为成对作品，七段线结构与彩宝偏移镶嵌提高制作复杂度。",
  },
  {
    id: "n-0303",
    slug: "seventh-light-watch-n-0303",
    serial: "N-0303",
    title: "Seventh Light Belonging Watch",
    zhTitle: "第七日归属腕表",
    seriesId: "seventh-light",
    category: "watch",
    inspiration: "时间让光有了归处。",
    concept:
      "轻薄珠宝腕表以贝母盘面和七枚极细时标表达倒计时，表冠旁的偏移彩宝让时间不再只是计量，而是归属发生的瞬间。",
    materials: ["玫瑰金", "铂金", "贝母", "彩色宝石"],
    craft: ["鎏金", "鎏彩", "钢琴烤漆"],
    startPrice: 5999,
    currentPrice: 5999,
    depositAmount: 520,
    bidIncrement: 220,
    bids: 0,
    endsAt: "2026-05-30T22:00:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0303-seventh-light-watch.png",
    sizing: "腕表表带支持多档调节，交付前按腕围确认孔位或链节。",
    engraving: "表背刻印 N-0303。",
    pricingBasis: "腕表品类体量和制作风险最高，贝母盘面、彩宝表冠和鎏彩工艺使其达到上限起拍价。",
  },
  {
    id: "n-0401",
    slug: "justice-of-one-brooch-n-0401",
    serial: "N-0401",
    title: "Justice of One Evidence Brooch",
    zhTitle: "唯一的证明证光胸针",
    seriesId: "justice-of-one",
    category: "brooch",
    inspiration: "不由多数定义，只由唯一确认。",
    concept:
      "雕金平衡线被一颗偏心孔雀石打破，再由景泰蓝色面重新建立秩序。它像一份无声证词，证明独特不需要多数同意。",
    materials: ["雕金", "孔雀石", "彩色宝石", "天然白钻"],
    craft: ["景泰蓝", "鎏金", "雕金"],
    startPrice: 5488,
    currentPrice: 5968,
    depositAmount: 480,
    bidIncrement: 200,
    bids: 12,
    endsAt: "2026-05-25T22:10:00+08:00",
    status: "live",
    image: "/assets/products/n-0401-justice-of-one-brooch.png",
    sizing: "胸针安全锁结构，不涉及尺码，可佩戴于多种面料。",
    engraving: "胸针背面刻印 N-0401。",
    pricingBasis: "雕金、孔雀石、景泰蓝和白钻组合，工艺复杂度高。",
  },
  {
    id: "n-0402",
    slug: "justice-of-one-cuff-n-0402",
    serial: "N-0402",
    title: "Justice of One Balance Bracelet",
    zhTitle: "唯一的证明衡线手环",
    seriesId: "justice-of-one",
    category: "bracelet",
    inspiration: "为被低估的独特，保留一次公平展示。",
    concept:
      "开放式雕金手环用孔雀石偏心打破平衡，景泰蓝线条重新建立秩序，让活口本身成为 Justice of One 的判断线。",
    materials: ["雕金", "黄金", "孔雀石", "天然白钻"],
    craft: ["景泰蓝", "鎏金", "雕金"],
    startPrice: 5788,
    currentPrice: 5788,
    depositAmount: 500,
    bidIncrement: 220,
    bids: 0,
    endsAt: "2026-05-29T20:40:00+08:00",
    status: "waiting",
    image: "/assets/products/n-0402-justice-of-one-cuff.png",
    sizing: "开放式活口手环，可按腕围微调，开口处为设计核心。",
    engraving: "手环内侧刻印 N-0402。",
    pricingBasis: "大体量手环，雕金、孔雀石、景泰蓝复合工艺，起拍价接近上限。",
  },
  {
    id: "n-0403",
    slug: "justice-of-one-ring-n-0403",
    serial: "N-0403",
    title: "Justice of One Verdict Ring",
    zhTitle: "唯一的证明裁光戒",
    seriesId: "justice-of-one",
    category: "ring",
    inspiration: "被证明之前，它已经成立。",
    concept:
      "雕金与铂金交错形成偏心活口戒，一枚深绿色宝石与景泰蓝细线构成证据般的光点。",
    materials: ["雕金", "铂金", "孔雀石", "天然白钻"],
    craft: ["景泰蓝", "雕金"],
    startPrice: 4988,
    currentPrice: 5528,
    depositAmount: 420,
    bidIncrement: 180,
    bids: 9,
    endsAt: "2026-05-24T23:10:00+08:00",
    status: "live",
    image: "/assets/products/n-0403-justice-of-one-ring.png",
    sizing: "活口戒臂，可按佩戴者手寸微调；偏心结构是设计特征。",
    engraving: "戒臂内侧刻印 N-0403。",
    pricingBasis: "戒指体量中高，雕金与景泰蓝细线工艺复杂，并使用孔雀石与白钻。",
  },
];

export const liveProducts = products.filter((product) => product.status !== "sold");
export const soldProducts = products.filter((product) => product.status === "sold");

export const adminMetrics: AdminMetric[] = [
  { label: "Live Auctions", value: "10", detail: "6 active bids, 4 waiting for first bid" },
  { label: "Story Series", value: "08", detail: "Ready for IP, short drama, game extension" },
  { label: "Pending Settlement", value: "$18.4k", detail: "Stripe deposit plus USDT balance review" },
  { label: "Generated Drafts", value: "24", detail: "Story seeds with image-generation briefs awaiting curator selection" },
];

export function getSeries(seriesId: string) {
  return storySeries.find((series) => series.id === seriesId);
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
