services:
  - type: web
    name: noirven
    runtime: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start:render
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 25.2.1
      - key: NEXT_PUBLIC_SITE_URL
        value: https://noirven.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_IMAGE_MODEL
        value: gpt-image-1
      - key: BNB_USDT_RECEIVING_ADDRESS
        value: "0xbd00c3d12dB5840A403D2880039Cb1c86155F8cC"
